name: payment_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  collection: ^1.17.2
  fl_chart: ^0.64.0
  material_design_icons_flutter: ^7.0.7296
  barcode_widget: ^2.0.4
  shared_preferences: ^2.2.2
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
